# This file is machine-generated - editing it directly is not advised

julia_version = "1.11.5"
manifest_format = "2.0"

[[deps.A]]
deps = ["B"]
uuid = "1"
version = "1.0.0"

[[deps.B]]
uuid = "2"
version = "2.0.0"
